### ISSUE TITLE
Launcher Design Checklist

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-launcher#28]
Design File: https://www.figma.com/file/KjWhHsdjRU8Ih3Ib1m3t7B/Launcher?node-id=17-1116&t=8CkjVJeArmK6ekNI-0

SearchField Widget Design: https://www.figma.com/file/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=8195-15503&t=CxhHGKrTZe7wA1Gp-0

ListView Widget Design: https://www.figma.com/file/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=6671-4481&t=XS4QMBc6i6kbVfY3-0

- [x] Initial State (no apps) the bottom and top padding should be 24 px (currently different on top and bottom)
- [x] Starting Position is 16 pixels from the bottom of the top bar OR 16 pixels from top of the display if there is no top bar. Launches at the top of the screen to accommodate future on screen keyboards (OSKs) without moving launcher/applibrary overlays.
- [x] Top position does not move. The list expands from the bottom.
- [x] Search Widget: use libcosmic search widget
- [x] Use or match ListItems (or current equivalent name in libcosmic) for search results list with padding per design.
- [x] Results application name: First line "Application Name" | Second line "Type - Description"  - "Flatpak - Browse the World Wide Web" for Firefox for instance
- [x] Show an already open app first then launching a new instance of the app
- [ ] Highlight the first application with when the launcher is initiated or results shown. This is to indicate that pressing "Enter" will launch or switch to the first app in the list.
- [x] "Help" (?) results layout - see attached image. Let's copy this for now but it will eventually need design love.

![cosmic-launcher-help](https://user-images.githubusercontent.com/3430283/223885762-f9b34470-51b4-4f9f-9161-2944bea391b5.png)
